env: "local"
database:
  host: "localhost"
  port: "5436"
  user: "postgres"
  password: "postgres"
  dbname: "orders"
  sslmode: "disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s
kafka:
  brokers:
    - "localhost:9021"
    - "localhost:9022"
    - "localhost:9023"
  topic: "orders-topic"
  group_id: "ordes-group"